apiVersion: batch/v1
kind: CronJob
metadata:
  name: loader-cronjob
spec:
  schedule: "53 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
          - name: loader
            image: elhanine/loader1
            command: ["python", "/app/loader.py" ,"--host", "elasticsearch"]
            volumeMounts:
            - name: cdr-pvc1
              mountPath: /mnt/data/cdr/decoded
          volumes:
          - name: cdr-pvc1
            persistentVolumeClaim:
              claimName: cdr-pvc1
          restartPolicy: OnFailure
# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: loader-cronjob
# spec:
#   schedule: "44 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: loader
#             image: youssefaitrimouch/loader
#             volumeMounts:
#             - name: cdr-pvc1
#               mountPath: /mnt/data/cdr/decoded
#             env:
#             - name: DECODED_FOLDER
#               value: /mnt/data/cdr/decoded
#             - name: DATABASE_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secrets
#                   key: username
#             - name: DATABASE_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secrets
#                   key: password
#           volumes:
#           - name: cdr-pvc1
#             persistentVolumeClaim:
#               claimName: cdr-pvc1
#           restartPolicy: OnFailure

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: loader-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: loader
#   template:
#     metadata:
#       labels:
#         app: loader
#     spec:
#       containers:
#       - name: loader
#         image: youssefaitrimouch/loader
#         volumeMounts:
#         - name: cdr-pvc1
#           mountPath: /mnt/data/cdr/decoded
#         env:
#             - name: DECODED_FOLDER
#               value: /mnt/data/cdr/decoded
#             - name: DATABASE_USER
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secrets
#                   key: username
#             - name: DATABASE_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: mysql-secrets
#                   key: password
#       volumes:
#       - name: cdr-pvc1
#         persistentVolumeClaim:
#           claimName: cdr-pvc1

# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: loader-cronjob
# spec:
#   schedule: "45 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: loader
#             image: youssefaitrimouch/loader
#             imagePullPolicy: IfNotPresent
#             command: ["python"]
#             args: ["./loader.py"]
#             volumeMounts:
#             - name: cdr-data
#               mountPath: /mnt/data/cdr
#           restartPolicy: OnFailure
#           volumes:
#           - name: cdr-data
#             persistentVolumeClaim:
#               claimName: cdr-data-claim

