apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cdr-pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: cdr-pv1