apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.17.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"  # Change to the address of your Elasticsearch service if needed
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: ClusterIP
  selector:
    app: kibana
  ports:
    - protocol: TCP
      name: http
      port: 5601
      targetPort: 5601





















# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: kibana
#   labels:
#     app: kibana
# spec:
#   selector:
#     matchLabels:
#       app: kibana
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: kibana
#     spec:
#       containers:
#       - name: kibana
#         image: docker.elastic.co/kibana/kibana:7.13.1
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 5601
#         env:
#         - name: ELASTICSEARCH_URL
#           value: "http://elasticsearch:9200"
#         - name: ELASTICSEARCH_HOSTS
#           value: "http://elasticsearch:9200"
#         - name: ELASTICSEARCH_USERNAME
#           value: "elastic"
#         - name: ELASTICSEARCH_API_KEY
#           valueFrom:
#             secretKeyRef:
#               name: elasticsearch-api-secret
#               key: api-secret
#         - name: ELASTICSEARCH_PASSWORD
#           value: "kibana"
#         - name: SERVER_NAME
#           value: "kibana.monitor.com" # Remplacez par votre nom de domaine ou adresse IP
#         - name: SERVER_PORT
#           value: "5601"
#         - name: ELASTICSEARCH_API_KEY
#           valueFrom:
#             secretKeyRef:
#               name: elasticsearch-api-secret
#               key: api-secret
#               optional: true
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: kibana
#   labels:
#     app: kibana
# spec:
#   type: ClusterIP
#   selector:
#     app: kibana
#   ports:
#     - protocol: TCP
#       name: http
#       port: 5601
#       targetPort: 5601
